### ISSUE TITLE
MSDK 5.8.0 Regression  - FlightControllerKey.KeyHeightLimitRange does not return values on Mini 3

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#265] opened 2024-02-14 17:37 UTC
## Environment

**Aircraft:** DJI Mini 3
**Controller:** DJI RC-N1
**Phone:** Samsung Galaxy S23 (SM-S911U1)
**MSDK Version:** 5.8.0

## Repro steps

1. Listen to results from `FlightControllerKey.KeyHeightLimitRange`
2. Connect to controller and turn on aircraft

**Expected result:** the range values emit

**Actual result:** nothing emits

Went back and tested MSDK 5.5.0  and it worked on there.

**Comment by dji-dev** [comment] 2024-02-18 12:14
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/100822'>Zendesk ticket #100822</a>:<br><br>We have successfully reproduced the issue. It will be escalated to our development team for resolution. You will be promptly notified once the issue is fixed.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment] 2024-02-26 02:49
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/100822'>Zendesk ticket #100822</a>:<br><br>This issue will be fixed in the next release. Please be patient and wait for the new version to be released.
<br><p><em><small>°°°</small></em></p>

**Closed as completed** 2024-06-03 07:42 UTC
