### ISSUE TITLE
Weird gimbal behaviour when rotating by a slow speed on high zoom levels

### ISSUE THREAD

**Issue by AppDev999** [dji-sdk/Mobile-SDK-Android-V5#320] opened 2024-04-23 06:20 UTC
I was playing around with my **M30**, and found something weird.
I zoomed in to approximately 160X, and tried to rotate the gimbal by touch-and-hold the screen of the RC.
if the offset of my finger is small (want to rotate slowly), the gimbal start to oscillate back and forth a few times, and suddenly after a few seconds it rotates by a higher speed to a relatively large angle!
I also tried the official **dji pilot2** application, and it has the exact same problem
note that rotating the gimbal by using the left/right dials works perfectly, the rotation is very smooth and accurate

thanks in advance

**Comment by dji-dev** [comment] 2024-04-23 12:40
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105769'>Zendesk ticket #105769</a>:<br><br>This should be a problem caused by the different control links between the App and the remote controller. In fact, the H20T also has this issue. If you want to achieve the same effect in the software as with the remote controller, the aircraft needs to be modified, as this issue cannot be resolved in the software.
<br><p><em><small>°°°</small></em></p>

**Comment by AppDev999** [comment] 2024-04-23 13:28
Thank you for your prompt response.

Actually, this is concerning. I really need to address this issue, as I did not fully understand everything you mentioned. Therefore, I have a few questions:

1. What do you mean by "different control links"? Are you suggesting that there are two separate links, one of which I do not have access to?
2. Could you clarify what you mean by "modifying the aircraft"?
3. Is it possible to adjust the PID controller parameters for the gimbal?

Thanks you.

**Comment by dji-dev** [comment] 2024-04-24 12:37
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105769'>Zendesk ticket #105769</a>:<br><br>1. What do you mean by "different control links"? Are you suggesting that there are two separate links, one of which I do not have access to? -- You can think of the app not being able to achieve the same level of control as the remote control, as if the remote control is using a different control method.
2. Could you clarify what you mean by "modifying the aircraft"?  -- That means drone engineers need to optimize the drone, that is, fix the issues you described.
3. Is it possible to adjust the PID controller parameters for the gimbal?  -- If you are referring to a high zoom factor, I believe it is not achievable. Dragging the gimbal on the app interface actually corresponds to KeyRotateBySpeed. However, even when using KeyRotateByAngle with a small rotation angle at this point, the gimbal remains unresponsive.
<br><p><em><small>°°°</small></em></p>

**Closed as completed** 2024-09-27 03:09 UTC
